name: Publish to NuGet

on:
  push:
    branches:
      - main  # Trigger the workflow on push or pull request, but only for the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@42

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x  # Install the .NET version required

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack
      run: dotnet pack --no-build --configuration Release -p:PackageVersion=1.0.${{ github.run_number }} -p:IncludeSymbols=false

    - name: Push
      run: dotnet nuget push "**/*.nupkg" --NoSymbols --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json